permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Fat Black Cat Studio"
  description: |
  Portfolio Website for the Fat Black Cat Studio Team.
  font_url: ""
  colors:
    background: "--color-primary-light"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      fdfsf
    typefaces.secondary: |
      sefef
    colors.primary: |
      The primary colours represent the fat black cat's fur and should be used in headings, backgrounds, buttons, banners, etc.
    colors.secondary: |
      The secondary colours represent the fat black cat's eyes and should be used to highlight elements, make an element stand out more etc.
