title: "Buttons"
description: |
  Buttons should only be used when there are obvious actions that is required. They are primarily for call-to-actions for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      These are the default buttons. They should be used on primarily light backgrounds.
    fields:
      - name: text
        type: string
        example: "Fat Black Cat"
  light:
    title: "Light"
    description: |
      These are the secondary buttons. They should be used on primarily dark backgrounds.
    fields:
      - name: text
        type: string
        example: "Fat Black Cat"
  ghost:
    title: "Ghost"
    description: |
      This button should be used with images and for more optional actions.
    fields:
      - name: text
        type: string
        example: "Fat Black Cat"
  hamburger:
    title: "Hamburger"
    description: |
      This button is for the mobile version for the navigation bar.
  email:
    title: "Email"
    description: |
      This button is to directly send us an email.
  instagram:
    title: "Instagram"
    description: |
      This button is to link to Instagram.
  facebook:
    title: "Facebook"
    description: |
      This button is to link to Facebook.
