title: "Cards"
description: |
  Buttons should only be used when there are obvious actions that is required. They are primarily for call-to-actions for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      These are the default cards. They should be used for images with a header.
    fields:
      - name: heading
        type: string
        example: "Coming soon"
      - name: image
        type: string
        example: "logo-horizontal.svg"
  social-btns:
    title: "Social Media"
    description: |
      This is for our social media links.
